INSERT INTO series (title, author_id, subgenre_id) VALUES ("percy jackson", 1, 3);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("vladimir todd", 2, 5);
INSERT INTO books (title, year, series_id) VALUES ("book 1", 2020, 1);
INSERT INTO books (title, year, series_id) VALUES ("book 2", 2020, 2);
INSERT INTO books (title, year, series_id) VALUES ("book 3", 2020, 1);
INSERT INTO books (title, year, series_id) VALUES ("book 4", 2020, 3);
INSERT INTO books (title, year, series_id) VALUES ("book 5", 2020, 1);
INSERT INTO books (title, year, series_id) VALUES ("book 6", 2020, 6);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Obi-Wan", "Hello there", "human", 3);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Palpatine", "I am the Senate!", "human", 4);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Anikan", "I don't like sand.", "human", 7);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Darth Vader", "No, I am your father!", "human", 3);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Jar Jar Binks", "Meesa your humble servant!", "Gungan", 3);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Maul", "KENOBIIIIII!!!1", "Dathomirian Zabrak", 3);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Yoda", "Do or do not, there is no try.", "unknown", 3);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Chewbacca", "*wookie sounds*", "human", 3);
INSERT INTO subgenres (name) VALUES ("scifi");
INSERT INTO subgenres (name) VALUES ("historical");
INSERT INTO authors (name) VALUES ("George Lucas");
INSERT INTO authors (name) VALUES ("Rick Riordan");
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
INSERT INTO character_books (book_id, character_id) VALUES (2,5);
